<?php if ($this->pageCount): ?>
    <div class="ui pagination menu">
    <!-- Previous page link -->
    <?php if (isset($this->previous)): ?>
        <a class="item" href="<?php echo $this->url(array('page' => $this->previous)); ?>">&lt;</a>
    <?php endif; ?>

     <!-- Numbered page links -->
    <?php foreach ($this->pagesInRange as $page): ?>
        <?php if ($page != $this->current): ?>
            <a class="item" href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a>
        <?php else: ?>
            <a class="active item" href="#"><?php echo $page; ?></a>
        <?php endif; ?>
    <?php endforeach; ?>

    <!-- Next page link -->
    <?php if (isset($this->next)): ?>
        <a class="item" href="<?php echo $this->url(array('page' => $this->next)); ?>">&gt;</a>
    <?php endif; ?>
    </div>
<?php endif; ?>